### ISSUE TITLE
Числа в массиве могут повторяться

### ISSUE THREAD

**Issue by sau412** [SvetlanaMaeva/HW_8#1]
В приведённой программе на момент коммита [473aa1f](https://github.com/SvetlanaMaeva/HW_8/commit/473aa1f350bd3d9a9ff01434e8dc01cc8380aa41) для массива 2x2x2 числа могут повториться с вероятностью около 8,5%.

Чтобы числа не повторялись, можно было бы завести дополнительный массив со списком чисел, и проверять что очередное число не в массиве. Так же в этом случае максимальный размер массива будет ограничен 4x4x4, так как при массиве 5x5x5 нужно сгенерировать 125 (5^3) чисел, а это больше, чем целых чисел в интервале [10;90].

**Comment by SvetlanaMaeva** [comment]
Да, я знаю об этом косяке) но это скорее неправильно сформулирована задача, т.к. с преподавателем этот момент обсуждали перед написанием ДЗ, он уточнил, что имеется ввиду вариант просто с рандомными числами) Задания на курс пишут методисты, а уточняют условия уже преподы, не всегда во мнении они сходятся :)
А ты очень внимательный)
